### ISSUE TITLE
export_core_vtk_line error

### ISSUE THREAD

**Issue by mlaloux** [opengeostat/pygslib#3]
I am sorry but when I try `mydholedb.export_core_vtk_line('CMP', 'cmp.vtk')` in the tutorial, the result is 
```
AttributeError                            Traceback (most recent call last)
<ipython-input-29-09f1873a59b1> in <module>()
      3 #mydholedb.export_core_vtk_line('CMP', 'cmp.vtk', nanval=0, title = '')
      4 #see(mydholedb.export_core_vtk_line)
----> 5 mydholedb.export_core_vtk_line('CMP', 'cmp.vtk')

cython_code/drillhole.pyx in pygslib.drillhole.Drillhole.export_core_vtk_line (cython_code/drillhole.c:32985)()

cython_code/drillhole.pyx in pygslib.drillhole.Drillhole.export_core_vtk_line (cython_code/drillhole.c:32636)()

AttributeError: SetInputData
```

**Comment by opengeostat** [comment]
Can you please check the VTK version you are using? For example, using this code: 

```
from __future__ import print_function
import vtk
print(vtk.vtkVersion.GetVTKSourceVersion())
```

I was not able to reproduce this error with VTK 6.3 and Python 2.7 or VTK 7. and Python 3.5.

**Comment by mlaloux** [comment]
Ok, it don't work with VTK  5.10.1 but yes with VTK 7 (Python 2.7.x)

**Comment by opengeostat** [comment]
Hi mlaloux, 

Thank you for let me know. I added requirement for VTK >= 6 at conda recipes (*.yaml files).

**Comment by lltnryn** [comment]
I am getting similar error while using  pygslib 0.0.0.4.0 and vtk 7.1.1.
Please suggest me a solution, thanks 
Traceback (most recent call last):

  File "<ipython-input-5-317c3c17013f>", line 1, in <module>
    runfile('C:/Users/MSI/.spyder/temp.py', wdir='C:/Users/MSI/.spyder')

  File "C:\Users\MSI\Anaconda2\envs\py2.7\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 704, in runfile
    execfile(filename, namespace)

  File "C:\Users\MSI\Anaconda2\envs\py2.7\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 93, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "C:/Users/MSI/.spyder/temp.py", line 35, in <module>
    mydholedb.export_core_vtk_line('CMP', 'cmp.vtk', title = 'Drillhole created in PyGSLIB')

AttributeError: 'pygslib.drillhole.Drillhole' object has no attribute 'export_core_vtk_line'

**Comment by opengeostat** [comment]
Hi @lltnryn `export_core_vtk_line` was renamed `intervals2vtk`. Sorry for any inconvenient, I should probably create an alias function to ensure back compatibility.
